server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${MS_AUTH_URI:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        - id: orders-service
          uri: ${MS_ORDERS_URI:http://localhost:8082}
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: ${MS_INVENTORY_URI:http://localhost:8083}
          predicates:
            - Path=/api/inventario/**

        - id: shipping-service
          uri: ${MS_SHIPPING_URI:http://localhost:8084}
          predicates:
            - Path=/api/envios/**

        - id: tracking-service
          uri: ${MS_TRACKING_URI:http://localhost:8085}
          predicates:
            - Path=/api/tracking/**

        - id: notification-service
          uri: ${MS_NOTIFICATION_URI:http://localhost:8086}
          predicates:
            - Path=/api/notificaciones/**